workflows:
  ios-development:
    name: iOS Development Build
    max_build_duration: 120
    environment:
      node: 20.19.4
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install --force
          npm list expo
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
      - name: Verify setup
        script: |
          npx expo --version
          node -v
          npm -v
      - name: Prebuild iOS without Firebase
        script: |
          cp app.json app.json.backup
          sed -i 's/"@react-native-firebase\/app",//g' app.json
          sed -i 's/"@react-native-firebase\/messaging",//g' app.json
          npx expo prebuild --platform ios
          mv app.json.backup app.json
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Manually add Firebase to AppDelegate
        script: |
          cd ios
          PROJECT_DIR=$(find . -name "AppDelegate.swift" -exec dirname {} \;)
          if [ -n "$PROJECT_DIR" ]; then
            echo "Found AppDelegate at: $PROJECT_DIR"
            echo "import FirebaseCore" >> "$PROJECT_DIR/AppDelegate.swift"
            echo "FirebaseApp.configure()" >> "$PROJECT_DIR/AppDelegate.swift"
            cat "$PROJECT_DIR/AppDelegate.swift"
          else
            echo "AppDelegate.swift not found, listing ios directory:"
            find . -name "*.swift" -type f
          fi
      - name: Set up code signing
        script: |
          keychain initialize
      - name: Build iOS app
        script: |
          cd ios
          WORKSPACE=$(find . -name "*.xcworkspace" | head -n 1)
          SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list | grep -A 100 "Schemes:" | grep -v "Schemes:" | head -n 1 | xargs)
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -destination generic/platform=iOS \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            archive
      - name: Export development IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            -exportPath $CM_BUILD_DIR/export \
            -exportOptionsPlist ios/*/exportOptions.plist
    artifacts:
      - export/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com