workflows:
  ios-development:
    name: iOS Development Build
    max_build_duration: 120
    environment:
      node: 20.19.4
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install --force
          npm list expo
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
      - name: Verify setup
        script: |
          npx expo --version
          node -v
          npm -v
      - name: Prebuild iOS without Firebase
        script: |
          cp app.json app.json.backup
          sed -i 's/"@react-native-firebase\/app",//g' app.json
          sed -i 's/"@react-native-firebase\/messaging",//g' app.json
          npx expo prebuild --platform ios
          mv app.json.backup app.json
      - name: Fix Podfile for Firebase
        script: |
          cd ios
          echo "use_modular_headers!" > Podfile.tmp
          echo "use_frameworks! :linkage => :static" >> Podfile.tmp
          echo "" >> Podfile.tmp
          cat Podfile >> Podfile.tmp
          mv Podfile.tmp Podfile
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up code signing
        script: |
          keychain initialize
      - name: Build iOS app
        script: |
          cd ios
          WORKSPACE=$(find . -name "*.xcworkspace" | head -n 1)
          SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list | grep -A 100 "Schemes:" | grep -v "Schemes:" | head -n 1 | xargs)
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -destination generic/platform=iOS \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            archive
      - name: Export development app
        script: |
          echo "Searching for .app files..."
          find $CM_BUILD_DIR -name "*.app" -type d
          echo "Archive contents:"
          ls -la $CM_BUILD_DIR/app.xcarchive/
          echo "Products directory:"
          ls -la $CM_BUILD_DIR/app.xcarchive/Products/ || echo "No Products directory"
          echo "Applications directory:"
          ls -la $CM_BUILD_DIR/app.xcarchive/Products/Applications/ || echo "No Applications directory"
          
          # Create export directory
          mkdir -p $CM_BUILD_DIR/export
          
          # Find and copy the actual .app file wherever it is
          APP_FILE=$(find $CM_BUILD_DIR -name "*.app" -type d | head -n 1)
          if [ -n "$APP_FILE" ]; then
            echo "Found app at: $APP_FILE"
            cp -r "$APP_FILE" $CM_BUILD_DIR/export/
          else
            echo "No .app file found!"
            exit 1
          fi
    artifacts:
      - export/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com