workflows:
  ios-development:
    name: iOS Development Build
    max_build_duration: 120
    environment:
      node: 20.19.4
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install --force
          npm list expo
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
      - name: Verify setup
        script: |
          npx expo --version
          node -v
          npm -v
      - name: Prebuild iOS without Firebase
        script: |
          cp app.json app.json.backup
          sed -i 's/"@react-native-firebase\/app",//g' app.json
          sed -i 's/"@react-native-firebase\/messaging",//g' app.json
          npx expo prebuild --platform ios
          mv app.json.backup app.json
      - name: Fix Podfile for Firebase
        script: |
          cd ios
          echo "use_modular_headers!" > Podfile.tmp
          echo "use_frameworks! :linkage => :static" >> Podfile.tmp
          echo "" >> Podfile.tmp
          cat Podfile >> Podfile.tmp
          mv Podfile.tmp Podfile
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up code signing
        script: |
          keychain initialize
      - name: Build iOS app
        script: |
          cd ios
          WORKSPACE=$(find . -name "*.xcworkspace" | head -n 1)
          SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list | grep -A 100 "Schemes:" | grep -v "Schemes:" | head -n 1 | xargs)
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Debug \
            -destination generic/platform=iOS \
            -derivedDataPath ./build \
            build
      - name: Export development app
        script: |
          cd ios
          echo "Searching in Build directory..."
          find ./build/Build -name "*.app" -type d 2>/dev/null || echo "No .app in Build directory"
          
          echo "Searching entire build tree..."
          find ./build -name "*.app" -type d -exec ls -la {} \;
          
          echo "Looking for Products directory..."
          find ./build -name "Products" -type d -exec ls -la {} \;
          
          echo "Build/Products contents:"
          ls -la ./build/Build/Products/ 2>/dev/null || echo "No Build/Products directory"
          
          echo "Intermediates contents:"
          find ./build/Build/Intermediates* -name "*.app" -type d 2>/dev/null || echo "No .app in Intermediates"
          
          # Try to find any executable or bundle
          echo "Looking for any iOS build products..."
          find ./build -name "*SynciTMobile*" -type d
          
          # Create export directory anyway
          mkdir -p $CM_BUILD_DIR/export
          
          # Look for the actual build product
          APP_FILE=$(find ./build -name "*.app" -type d | head -n 1)
          if [ -n "$APP_FILE" ]; then
            echo "Found app at: $APP_FILE"
            cp -r "$APP_FILE" $CM_BUILD_DIR/export/
          else
            echo "Still no .app file found, checking if build actually succeeded..."
            echo "Checking for any build products:"
            find ./build -name "*" -type f | grep -i syncit | head -10
          fi
    artifacts:
      - export/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com